name: Release ArabicaCliento

on:
  push:
    tags:
      - 'v*' # v0.1 and next...
      
jobs:
  release:
    
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - run: dotnet restore
        
      - name: Make Arabica Coffee
        run: dotnet build
        
      - name: Pour coffee
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Tag
          release_name: Version ${{ github.ref_name }}
          draft: true
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ArabicaCliento/bin/Debug/net9.0/ArabicaCliento.dll
          asset_name: ArabicaCliento.dll
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Bring coffee to release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
